In [3]:
import pandas as pd
pd.set_option("display.max_colwidth", 100)

In [4]:
df = pd.read_csv('./sample_text.csv')
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [5]:
df.shape

(8, 2)

In [6]:
from sentence_transformers import SentenceTransformer

In [7]:
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

c:\Users\mbantwal\AppData\Local\anaconda3\envs\python_3.10.12\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()


In [8]:
vectors

array([[-0.00247397,  0.03626722, -0.05290459, ..., -0.09152356,
        -0.03970002, -0.04330491],
       [-0.03357267,  0.00980518, -0.03250131, ..., -0.05165466,
         0.02245885, -0.03156183],
       [-0.01865327, -0.04051307, -0.0123539 , ...,  0.00610588,
        -0.07179645,  0.02773852],
       ...,
       [-0.00066458,  0.04252128, -0.05645509, ...,  0.01315468,
        -0.03183568, -0.04357664],
       [-0.03317152,  0.03252458, -0.02484841, ...,  0.0117442 ,
         0.05747125,  0.00571022],
       [-0.00166395,  0.00413828, -0.04597083, ...,  0.02008527,
         0.05656243, -0.00161596]], dtype=float32)

In [9]:
vectors.shape

(8, 768)

In [10]:
dim = vectors.shape[1]
dim

768

In [11]:
import faiss

index = faiss.IndexFlatL2(dim)

In [12]:
index.add(vectors)

In [13]:
index

<faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000001E4EA146130> >

In [23]:
# search_query = "I want to buy a polo t-shirt"
search_query = "looking for places to visit during the holidays"
# search_query = "An apple a day keeps the doctor away"
vec = encoder.encode(search_query)
vec.shape

(768,)

In [24]:
import numpy as np
svec = np.array(vec).reshape(1, -1)
svec.shape

(1, 768)

In [25]:
faiss.normalize_L2(svec)

In [26]:
distances, I = index.search(svec, k=2)
distances

array([[0.92737293, 1.1601744 ]], dtype=float32)

In [27]:
I

array([[6, 7]], dtype=int64)

In [28]:
I.tolist()

[[6, 7]]

In [29]:
row_indices = I.tolist()[0]
row_indices

[6, 7]

In [30]:
df.loc[row_indices]

text  \
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
6   Travel  
7   Travel

In [31]:
search_query

'looking for places to visit during the holidays'